//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Visual.Galaxy.Framework.Community.KernelTeam")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © 2017-2021 by  Visual Galaxy Framework Community Kernel Developer Team" +
    ".")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Class Framework for great Applications.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.6")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("Visual.Galaxy.Framework")]
[assembly: System.Reflection.AssemblyTitleAttribute("Visual.Galaxy.Framework")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.6")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/Tipplin/Visual.Galaxy.Framework")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows7.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows7.0")]

// Von der MSBuild WriteCodeFragment-Klasse generiert.

